language: swift
xcode_workspace: SwiftYNAB.xcworkspace
xcode_scheme: SwiftYNAB
xcode_destination: platform=iOS Simulator,OS=11.0.1,name=iPhone X
osx_image: xcode10.2
after_success:
  - bash <(curl -s https://codecov.io/bash)